apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-04T13:30:52Z"
  name: aws-auth
  namespace: kube-system
  uid: ff0868ad-3c79-47b5-b204-ff07d5b77900
data:
  mapRoles: |
    - users:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-lYugMxe9PNpC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::315069654700:user/ramesh
      username: ramesh
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::315069654700:user/ramesh
      username: suresh
